apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: megatest45-poi-map-app-dev
  annotations:
    argocd/app-name: megatest45-poi-map-app-dev
    backstage.io/kubernetes-id: megatest45-poi-map-app
    backstage.io/kubernetes-namespace: megatest45
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: rhdh-atl/megatest45-frontend
    janus-idp.io/tekton-enabled: 'true'
  tags:
    - typescript
    - angular
    - workshop
  links:
    - url: https://console-openshift-console.apps.j0i9yf30.eastus2.aroapp.io/dev-pipelines/ns/megatest45/
      title: Pipelines
      icon: web
    - url: https://console-openshift-console.apps.j0i9yf30.eastus2.aroapp.io/k8s/ns/megatest45/deployments/megatest45-poi-map-app
      title: Deployment
      icon: web
    - url: https://devspaces.apps.j0i9yf30.eastus2.aroapp.io/#https://github.com/rhdh-atl/megatest45-frontend?che-editor=che-incubator/che-code/latest&devfilePath=.devfile-vscode.yaml
      title: OpenShift Dev Spaces (VS Code)
      icon: web
    - url: http://megatest45-poi-map-app-megatest45.apps.j0i9yf30.eastus2.aroapp.io
      title: Map
      icon: web
spec:
  type: service
  lifecycle: production
  owner: "user:default/megatest45"
  system: workshop-system-megatest45
  consumesApis:
    - gateway-api-megatest45
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: workshop-system-megatest45
  tags:
    - backstage
    - janus-idp
    - openshift
    - workshop
    - rh-summit
spec:
  owner: "user:default/megatest45"
